### ISSUE TITLE
README.md has strange encoding

### ISSUE THREAD

**Issue by sgouache** [KhiopsML/khiops-samples#1]
When loading khiops sample data into a jupyter notebook, the toplevel README.md cannot be displayed. If clicked, jupyter shows the following message: **README.md is not UTF-8 encoded**

Inspecting the file with
```
$ file README.md 
README.md: ISO-8859 text
```

If file is converted e.g. with iconv like so:
`$ iconv -f ISO-8859-1 -t UTF-8//TRANSLIT README.md -o README_converted.md
`
the converted file displays OK.

**Comment by folmos-at-orange** [comment]
Done in 4572983
